package com.campushub.report.model;

public enum ReportReason {
    FAKE_LISTING,
    WRONG_PRODUCT_DETAILS,
    MISLEADING_IMAGES,
    SUSPICIOUS_SELLER,
    STOLEN_ITEM_SUSPICION,
    PROHIBITED_ITEM,
    ABUSIVE_CONTENT,
    DUPLICATE_LISTING,
    PRICE_SCAM,
    SUSPICIOUS_BEHAVIOR,
    FAKE_IDENTITY,
    SCAM_ATTEMPT,
    HARASSMENT,
    REPEATED_FAKE_LISTINGS,
    PAYMENT_RELATED_ISSUE,
    UNSAFE_PICKUP_BEHAVIOR,
    ABUSIVE_LANGUAGE,
    FAKE_REVIEW,
    SPAM,
    PERSONAL_INFORMATION_EXPOSED,
    IRRELEVANT_REVIEW,
    FALSE_CLAIM,
    OTHER
}
